# multi-repo
additionalRepositories:
  - url: https://github.com/datagir/nosgestesclimat-site

tasks:
  - name: frontend
    before: |
      cd ../nosgestesclimat-site
    init: |
      yarn
    command: |
      # Launch 
      yarn start
